#!/bin/sh

if [ $# -lt 1 ]; then
	echo "makefile type is need!"
	exit 1
fi

mfName=$1
# 需要写成兼容 WSL 和 linux物理机的形式
# mfScriptsPath="~/scripts/makefile"
# mfToolsPath="~/tools/make"
mfScriptsPath="/mnt/c/User/Isaac/scripts/makefile"
mfToolsPath="/mnt/c/User/Isaac/tools/make"

if [ -d mfScriptsPath ]; then
    echo "The scripts path is exist"
else
    echo "The scripts path is not exist"
fi


if [ -d mfToolsPath ]; then
    echo "The tools path is exist"
else
    echo "The tools path is not exist"
fi










